import { digestSummary, type Filters } from "@/lib/db/queries";

function pct(n: number, total: number) { return total ? Math.round((n / total) * 100) : 0; }

export function buildDigestHtml(
  dbPath: string | undefined, period: "weekly" | "monthly", f: Filters, prevWindowStart: number,
): { subject: string; html: string } {
  const s = digestSummary(dbPath, f, prevWindowStart);
  const k = s.kpis;
  const label = period === "weekly" ? "Weekly" : "Monthly";
  const subject = `${label} DMARC digest - ${pct(k.dmarcPass, k.totalMessages)}% compliant, ${k.totalMessages.toLocaleString()} messages`;

  const sourceRows = s.topSources.map((src) => `
    <tr>
      <td style="padding:6px 10px;font-family:monospace;font-size:12px">${src.sourceIp}</td>
      <td style="padding:6px 10px;text-align:right">${src.messages.toLocaleString()}</td>
      <td style="padding:6px 10px;text-align:right;color:#16a34a">${src.pass.toLocaleString()}</td>
      <td style="padding:6px 10px;text-align:right;color:#dc2626">${src.fail.toLocaleString()}</td>
    </tr>`).join("");

  const newSources = s.newSources.length
    ? `<p style="margin:8px 0;color:#b45309"><strong>${s.newSources.length} new sending source(s)</strong>: ${s.newSources.slice(0, 15).join(", ")}</p>`
    : `<p style="margin:8px 0;color:#64748b">No new sending sources this period.</p>`;

  const html = `
  <div style="font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:640px;margin:0 auto;color:#0f172a">
    <h1 style="font-size:20px">${label} DMARC digest</h1>
    <table style="width:100%;border-collapse:collapse;margin:16px 0">
      <tr>
        <td style="padding:12px;border:1px solid #e2e8f0"><div style="font-size:12px;color:#64748b">Messages</div><div style="font-size:22px;font-weight:700">${k.totalMessages.toLocaleString()}</div></td>
        <td style="padding:12px;border:1px solid #e2e8f0"><div style="font-size:12px;color:#64748b">DMARC pass</div><div style="font-size:22px;font-weight:700">${pct(k.dmarcPass, k.totalMessages)}%</div></td>
        <td style="padding:12px;border:1px solid #e2e8f0"><div style="font-size:12px;color:#64748b">SPF / DKIM</div><div style="font-size:22px;font-weight:700">${pct(k.spfPass, k.totalMessages)}% / ${pct(k.dkimPass, k.totalMessages)}%</div></td>
      </tr>
      <tr>
        <td style="padding:12px;border:1px solid #e2e8f0"><div style="font-size:12px;color:#64748b">Quarantined</div><div style="font-size:22px;font-weight:700">${k.quarantined.toLocaleString()}</div></td>
        <td style="padding:12px;border:1px solid #e2e8f0"><div style="font-size:12px;color:#64748b">Rejected</div><div style="font-size:22px;font-weight:700">${k.rejected.toLocaleString()}</div></td>
        <td style="padding:12px;border:1px solid #e2e8f0"><div style="font-size:12px;color:#64748b">Sources</div><div style="font-size:22px;font-weight:700">${k.distinctSources.toLocaleString()}</div></td>
      </tr>
    </table>
    ${newSources}
    <h2 style="font-size:15px;margin-top:24px">Top sending sources</h2>
    <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0">
      <tr style="background:#f8fafc;text-align:left">
        <th style="padding:6px 10px">Source IP</th><th style="padding:6px 10px;text-align:right">Messages</th>
        <th style="padding:6px 10px;text-align:right">Pass</th><th style="padding:6px 10px;text-align:right">Fail</th>
      </tr>
      ${sourceRows}
    </table>
    <p style="margin-top:24px;font-size:12px;color:#94a3b8">Generated by your self-hosted DMARC Dashboard.</p>
  </div>`;

  return { subject, html };
}
